version: '3.1'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef